- hosts: awx
  become: true

  tasks:
  - name: 'Backup database with pg_dump'
    command: docker exec awx_postgres pg_dump -U awx -Fc awx
    register: dump

  - copy:
    content: "{{ dump.stdout }}"
    dest: "awx_db_{{ ansible_date_time.iso8601_micro }}.dump"
  