# https://github.com/geerlingguy/ansible-role-awx
# https://github.com/geerlingguy/ansible-role-docker

- hosts: awx
  become: true

  vars:
    nodejs_version: "6.x"
    docker_install_compose: true
    docker_compose_version: "1.25.4"
    docker_compose_path: /usr/local/bin/docker-compose
    pip_install_packages:
      - name: docker-compose
    awx_repo: https://github.com/ansible/awx.git
    awx_repo_dir: "/opt/awx"
    awx_version: "9.3.0"
    awx_keep_updated: true
    awx_run_install_playbook: true
    postgres_data_dir: /var/lib/pgdocker

  roles:
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx